# Generated by Django 4.2 on 2025-09-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LedgerEntry',
            new_name='Ledger',
        ),
    ]
