# Generated by Django 4.2 on 2025-10-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_ledger_credit_amount_ledger_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='debit_amount',
        ),
        migrations.AddField(
            model_name='ledger',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ledger',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
