# Generated by Django 4.2 on 2025-11-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_remove_ledger_amount_remove_ledger_credit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit'), ('installment', 'Installment')], max_length=15, null=True),
        ),
    ]
