# Generated by Django 4.2 on 2025-10-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_balance_remove_customer_phone_and_more'),
        ('sales', '0004_invoice_grand_total_invoice_returned_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='returned_amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receiving_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='remaining_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.FloatField(),
        ),
    ]
