# Generated by Django 4.2 on 2025-10-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_invoice_returned_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
