# Generated by Django 4.2 on 2025-09-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_percentage', models.DecimalField(decimal_places=2, help_text='Selling % margin', max_digits=5)),
                ('buying_price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_percentage', models.DecimalField(decimal_places=2, help_text='Buying % margin', max_digits=5)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockins', to='products.product')),
            ],
        ),
    ]
