# Generated by Django 4.2 on 2025-09-09 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stockin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
